### PR TITLE
Keep Vault up at 16KB block size

### PR DESCRIPTION
**Pull request by andrewd-zededa**
Don't take default from mkfs.ext4

### CODE REVIEW

**Review by zedi-pramodh — APPROVED** [review]
LGTM.

But you need to update the PR in the master too. Erik had questions on performance issues.

**Comment by andrewd-zededa** [comment]
I'm going to hold off on merging this yet, my boot test isn't working.

**Review by zedi-pramodh — CHANGES_REQUESTED** [review]
Do not merge

**Comment by andrewd-zededa** [comment]
Closing this

**Pull request closed without merging**
