### PR TITLE
ZFS Vault Cleanup and eve_install_kubevirt_etcd_sizeGB boot option

### PR DESCRIPTION
**Pull request by andrewd-zededa**
Addition of new grub boot option 'eve_install_kubevirt_etcd_sizeGB' which specifies the size of the etcd zvol on kubevirt images. Cleanup of RESERVE_EVE_STORAGE_SIZEGB which is not used until first boot. Move kubevirt specific eve_install option constants to kubevirt.go. Parse both eve_install_kubevirt_reserve_for_eve_sizeGB and eve_install_kubevirt_etcd_sizeGB in vault handler_zfs.go before creating the zvols.
A few yetus errors were fixed in the process.

### CODE REVIEW

**Comment by zedi-pramodh** [comment]
In general changes are Ok to me. But I am skeptical of the approach to read from /proc/cmdline. Can we check with devt-eve if that remains constant forever ? Not sure if upgrades or reboots can change it or not

**Comment by andrewd-zededa** [comment]
@zedi-pramodh Ok waiting to hear back on that.  Currently domainmgr uses this process as well in getReservedCPUsNum().

**Comment by andrewd-zededa** [comment]
@zedi-pramodh usage of /proc/cmdline seems to have been cleared.  Latest commit also removes the kubevirt eve reserve setting since the new storage layout removes the motivation for it.

**Review by zedi-pramodh — APPROVED** [review]
LGTM

**Pull request merged**
