### PR TITLE
Extend event ttl to 24hr, dump in collect-info

### PR DESCRIPTION
**Pull request by andrewd-zededa**
Default is 1hr which drops useful debug info.

### CODE REVIEW

**Comment by zedi-pramodh** [comment]
Does this increase log sizes ? What are the side effects

**Comment by naiming-zededa** [comment]
I don't see the collect-info.sh collecting this 'event'

**Comment by naiming-zededa** [comment]
another thing for 'collect-info.sh' is that, even the image is 'kubevirt' type, but the k3s cluster may not be up at the time the collect-info is run, so it would be good to check if the cluster is reachable at the time, otherwise, I have seen it hang due the the cluster problem.

**Comment by andrewd-zededa** [comment]
@zedi-pramodh @naiming-zededa Missed adding collect-info to the commit, it is there now.  These events are stored in etcd so any size increase will be the db files in /var/lib/rancher/k3s/server/db/ which is on the 10GB zvol currently.

**Comment by andrewd-zededa** [comment]
> another thing for 'collect-info.sh' is that, even the image is 'kubevirt' type, but the k3s cluster may not be up at the time the collect-info is run, so it would be good to check if the cluster is reachable at the time, otherwise, I have seen it hang due the the cluster problem.

That is a good point, we could do simple health check against the kube api before issuing all the collect_kube_info and collect_longhorn_info.  I would suggest maybe we do an `eve exec kube kubectl cluster-info` which returns a non-zero code if the api is not responding. 

A few examples:

api server connection failure:
```
$ kubectl cluster-info
E1029 20:54:58.401774   67960 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
E1029 20:54:58.402295   67960 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
E1029 20:54:58.404315   67960 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
E1029 20:54:58.405257   67960 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused
E1029 20:54:58.406821   67960 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:6443/api?timeout=32s": dial tcp 127.0.0.1:6443: connect: connection refused

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
$ echo $?
1
```

successful api access:
```
[kube] root@36f5b4da-e82c-4b86-8f61-ce093f46f1af:/$ kubectl cluster-info
Kubernetes control plane is running at https://127.0.0.1:6443
CoreDNS is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
Metrics-server is running at https://127.0.0.1:6443/api/v1/namespaces/kube-system/services/https:metrics-server:https/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[kube] root@36f5b4da-e82c-4b86-8f61-ce093f46f1af:/$ echo $?
0
```

Curl could be used but we'll have to determine success off an error code since a simple get will be unauthorized.

For a system where api server isn't running:
```
$ curl -s https://127.0.0.1:6443
$ echo $?
7
```

or api server available with curl:
```
36f5b4da-e82c-4b86-8f61-ce093f46f1af:~# curl -s https://127.0.0.1:6443
36f5b4da-e82c-4b86-8f61-ce093f46f1af:~# echo $?
60
```

The curl man page states error code 7 is 'failed to connect to host' and 60 is 'Peer certificate cannot be authenticated with known CA certificates.'

**Review by naiming-zededa — APPROVED** [review]
LGTM

**Pull request merged**
